version: '3'
services:


  database:
    image: postgres:latest
#    restart: always
    ports:
      - "3306:3306"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: k@ycl0ck
      TZ: America/NewYork



  keycloak:
    image: keycloak-phone:snapshot
#    restart: always
    ports:
      - 8901:8080
    environment:
      SMS_PROVIDER_SERVER: twilio
      SMS_TOKEN_EXPIRES: 180
      SMS_HOUR_MAXIMUM: 300

      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: k@ycl0ck
      DB_VENDOR: postgres
      DB_PORT: 5432
    links:
      - database:database
    depends_on:
      - database

