apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
    name: keycloak-appui
spec:
  runPolicy: Serial
  source:
    dockerfile: |
      #Builder
      FROM maven:3.8.2-jdk-11 as builder
      RUN git clone https://github.com/open-sudo/keycloak-phone-provider.git
      RUN mvn package -f keycloak-phone-provider/pom.xml


      # Runner
      FROM quay.io/keycloak/keycloak:11.0.3

      RUN  curl -fSL https://repo1.maven.org/maven2/com/twilio/sdk/twilio/7.53.0/twilio-7.53.0.jar -o twilio-7.53.0.jar \
       && curl -fSL https://repo1.maven.org/maven2/org/ini4j/ini4j/0.5.4/ini4j-0.5.4.jar -o ini4j-0.5.4.jar \
       && curl -fSL https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/0.8.5/org.jacoco.agent-0.8.5-runtime.jar -o org.jacoco.agent-0.8.5-runtime.jar

      COPY --from=builder  /keycloak-phone-provider/target/modules/keycloak-phone-provider/main/keycloak-phone-provider.jar .
      COPY --from=builder  /keycloak-phone-provider/target/modules/keycloak-sms-provider-twilio/main/keycloak-sms-provider-twilio.jar .


      COPY --from=builder  /keycloak-phone-provider/target/module-add.cli cli/
      RUN $JBOSS_HOME/bin/jboss-cli.sh --file=cli/module-add.cli
      RUN rm -rf $JBOSS_HOME/standalone/configuration/standalone_xml_history/current

      COPY --from=builder  /keycloak-phone-provider/target/standalone/deployments/keycloak-phone-provider.resources.jar $JBOSS_HOME/standalone/deployments/
      USER root
      RUN chown -R 1000690000:root .
      RUN chown -R 1000690000:root /opt/jboss
      USER 1000690000
      ENV SMS_PROVIDER_SERVER=twilio
      ENV SMS_TOKEN_EXPIRES=180
      ENV SMS_HOUR_MAXIMUM=300
      ENV KEYCLOAK_USER=admin
      ENV KEYCLOAK_PASSWORD=admin
      ENV DB_ADDR=postgresql
      ENV DB_DATABASE=keycloak
      ENV DB_USER=keycloak
      ENV DB_PASSWORD=k@ycl0ck
      ENV DB_VENDOR=postgres
      ENV DB_PORT=5432

  strategy:
    type: Docker
    dockerStrategy:
      noCache: false
  output:
    to:
      kind: ImageStreamTag
      name: "keycloak-appui:latest"
