kind: ConfigMap
apiVersion: v1
metadata:
  name: keycloak-config 
  namespace: appui-backend-project
data:
      SMS_PROVIDER_SERVER: twilio
      SMS_TOKEN_EXPIRES: 180
      SMS_HOUR_MAXIMUM: 300
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: postgresql
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: k@ycl0ck
      DB_VENDOR: postgres
      DB_PORT: 5432
  
